version: '3.8'
services:
  backend:
    restart:
      
    build:
      context: ./backend
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 5555:5173
    depends_on:
      - backend